--- #YAML:1.4
name:              Data::Peek
version:           0.20
abstract:          Modified and extended debugging facilities
license:           perl
author:              
    - H.Merijn Brand <h.merijn@xs4all.nl>
generated_by:      Author
distribution_type: module
provides:
    Data::Peek:
        file:      Peek.pm
        version:   0.20
requires:     
    perl:          5.006
    DynaLoader:    0
build_requires:
    perl:          5.006
    Data::Dumper:  0
    Test::Harness: 0
    Test::More:    0
resources:
    license:       http://dev.perl.org/licenses/
meta-spec:
    version:       1.4
    url:           http://module-build.sourceforge.net/META-spec-v1.4.html
