--- #YAML:1.0
name:                    Data::Peek
version:                 0.32
abstract:                Modified and extended debugging facilities
license:                 perl
author:              
    - H.Merijn Brand <h.m.brand@xs4all.nl>
generated_by:            Author
distribution_type:       module
provides:
    Data::Peek:
        file:            Peek.pm
        version:         0.32
requires:     
    perl:                5.008
    DynaLoader:          0
recommends:
    perl:                5.012002
configure_requires:
    ExtUtils::MakeMaker: 0
build_requires:
    perl:                5.008
    Data::Dumper:        0
    Test::Harness:       0
    Test::More:          0
    Test::NoWarnings:    0
resources:
    license:             http://dev.perl.org/licenses/
    repository:          http://repo.or.cz/w/Data-Peek.git
meta-spec:
    version:             1.4
    url:                 http://module-build.sourceforge.net/META-spec-v1.4.html
